### ISSUE TITLE
run it with own domain owner

### ISSUE THREAD

**Issue by kintaro1981** [Real-Gecko/virtualmin-nginx-fpm#13]
how can I run each nginx-fpm instance with it's own owner?
it already does it?

**Comment by Real-Gecko** [comment]
Each time you create new virtual server Nginx and FPM configs are created, each FPM instance runs as domain owner:
![fpm-processes](https://cloud.githubusercontent.com/assets/2231969/14816664/fcfa6284-0bd3-11e6-934d-26fcc4f7a26d.png)
More info here https://github.com/Real-Gecko/virtualmin-nginx-fpm/issues/11

**Comment by kintaro1981** [comment]
ok, in my server with "top" I can see nginx running as www-data and php-fpm with virtual server owner's permission, can you confirm is the standard/right behavior? (I'm a newbie about nginx!)

**Comment by Real-Gecko** [comment]
100% right behavior.
