### ISSUE TITLE
Breaks script installs

### ISSUE THREAD

**Issue by aquada** [Real-Gecko/virtualmin-nginx-fpm#2]
I noticed this problem today and wondered if there was a way around it. 
`This script cannot be installed, as this virtual server does not meet its requirements : Webserver support for PHP is needed`

thanks for HTTPS implementation

**Comment by Real-Gecko** [comment]
A very interesing issue. Never met it. What kinda server you're running? What version of PHP?
 Can you please provide full scenario so I can reproduce it?

**Comment by aquada** [comment]
Really easy to reproduce. Install module  - Virtualmin, System Settings, Features and Plugins: Uncheck NGINX and NGINX SSL and check NGINX PHP-FPM. Create a Virtual Server, click on Install Script for server that has been created and try installing a script that requires PHP. eg phpmyadmin and you will get this message. 

The installer is checking for a valid webserver with PHP support and it doesn't recognise the installation when created through the virtualmin-nginx-fpm module. 

The only way round I can see is to disable NGINX PHP-FPM and re-enable NGINX virtualmin module or to manually install.

**Comment by Real-Gecko** [comment]
Ah, now I understand, interesting, I never tried script installers, I'll look into the way to fix that. For now I can only advise to install script manually.

**Comment by Real-Gecko** [comment]
Version 1.0.3 is out. Script installers now work. Tested with phpMyAdmin, RoundCube, SquirrelMail and X2Engine.
