### ISSUE TITLE
uninstalling

### ISSUE THREAD

**Issue by kintaro1981** [Real-Gecko/virtualmin-nginx-fpm#21]
@Real-Gecko uninstalling can hurt the configuration of fpm?
I now fpm is natively supported I switched all the domains to the core plugin and I would like to uninstall yours virtualmin-nginx-fpm.

**Comment by Real-Gecko** [comment]
If all your domains are switched, then you can uninstall it without and fear.

**Comment by 7starsone** [comment]
At the moment, I think that the only manifest issue is this:
https://www.virtualmin.com/node/51833

so, when a user tries to switch for the first time from fcgid...especially because there are no clear instructions on how to do it, yet...

**Comment by 7starsone** [comment]
and then, the default config for pools is very conservative (eg. pm.max_spare_servers = 5 for any virtual server...) and a direct fpm control panel is missing (even for root)

another weird thing I noticed is that a server is created at any hour o'clock (eg. 13:00 ...14:00) and I don't know why, is it a fpm feature?
