### ISSUE TITLE
Fill-in default values of 'Manage Nginx PHP-FPM website' page

### ISSUE THREAD

**Issue by chapmanjacobd** [Real-Gecko/virtualmin-nginx-fpm#4]
Then the user can choose to enable SSL without getting an error.

| Setting | Value |
| --- | --- |
| Number of child processes | 50 |
| The number of child processes to create on startup | 20 |
| The desired minimum number of idle processes | 5 |
| The desired maximum number of idle processes | 35 |
| The number of requests each child process should execute before respawning | 500 |

![capture](https://cloud.githubusercontent.com/assets/7908073/11316351/103f8862-903f-11e5-98ac-9cb80626cf4d.PNG)

**Comment by Real-Gecko** [comment]
I'm not sure what are you trying to say.

**Comment by chapmanjacobd** [comment]
lol. Sorry I didn't explain this issue very well.

The plugin wasn't filling in the default values on the "Manage Nginx
PHP-FPM website" page of a virtual server in Debian 8.

However, I tested it on CentOS 7 and it works like it should.

**Comment by Real-Gecko** [comment]
That's strange I use Debian 8 myself and it fills default values well. What version of plugin you use?

**Comment by chapmanjacobd** [comment]
1.0.4

**Comment by Real-Gecko** [comment]
Cannot reproduce it, actually this default settings are hardcoded in module code.
Does it happen when you create domain?
Or it happens when you edit PHP-FPM settings in `Services` menu link?

**Comment by chapmanjacobd** [comment]
When creating a domain. If you can't reproduce it, I wouldn't worry
about it. I already deleted the Debian server. You can just close the issue.

Thanks for the plugin! It helped me transition over to nginx.

**Comment by Real-Gecko** [comment]
You're welcome!
Feel free to reopen issue if things go wrong again.
